project:
  type: website

website:
  title: "app"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publikasjon.qmd
      - cv.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

